### ISSUE TITLE
The problem of training my own data

### ISSUE THREAD

**Issue by JieDengsc** [yizhongw/self-instruct#22]
Thanks for sharing!

I want to "self-instruct" using my Chinese data, but I can't call Open AI. If I want to use an existing model (such as LLAMA2), I can use this model to implement "self-instruct" locally offline. How do I modify the code? Or do you have any suggestions?

Thanks!

**Comment by shalchianmh** [comment]
There is a `gpt3_api.py` file which contains a function named make_requests, this function is imported whenever LM is needed,
you can read this file and create a similar file that does the same thing using Llama or any other models.

**Comment by JieDengsc** [comment]
Thanks, I got it.
