### ISSUE TITLE
Minor Grammatical Errors

### ISSUE THREAD

**Issue by atlasunified** [yizhongw/self-instruct#7]
Greetings!

Excellent code! I saw a few grammatical errors in some of your code that I figured I'd share with you.

on Prep:
Line 32 - Word misspelled. ign instead of ing.

on GPT:
Line 43 - there is a word capitalized after a comma.
Lines 74 and 79 - gpt is lowercase and the rest are upper case.

on Bootstrap:
Line 116 - Used 'GPT-3', however, other instances in your code refer to it as 'GPT3'.
Line 121 - 'missing quotes' around variable referenced.

on CLF:
Line 55 - 'missing quotes' around variable referenced.

Trivial in nature as it does not interfere with your code, but figured you may want some uniformity.

Regards,

Atlas

**Comment by yizhongw** [comment]
Thanks for pointing out the typos. They should be fixed now.
